---

mysql_packages:
  - python-mysqldb
mysql_login_user: "root"
mysql_login_password: "password"
mysql_login_host: "localhost"
mysql_login_port: 3306
mysql_user_host: "localhost"
mysql_user_hosts: ["{{ mysql_user_host }}"]
mysql_databases:
  - "{{ ECOMMERCE_DEFAULT_DB_NAME | default(None) }}"
  - "{{ INSIGHTS_DATABASE_NAME | default(None) }}"
  - "{{ ORA_MYSQL_DB_NAME | default(None) }}"
  - "{{ XQUEUE_MYSQL_DB_NAME | default(None) }}"
  - "{{ EDXAPP_MYSQL_DB_NAME | default(None) }}"
  - "{{ EDXAPP_MYSQL_CSMH_DB_NAME | default(None) }}"
  - "{{ EDX_NOTES_API_MYSQL_DB_NAME | default(None) }}"
  - "{{ PROGRAMS_DEFAULT_DB_NAME | default(None) }}"
  - "{{ ANALYTICS_API_DEFAULT_DB_NAME | default(None) }}"
  - "{{ ANALYTICS_API_REPORTS_DB_NAME | default(None) }}"
  - "{{ CREDENTIALS_DEFAULT_DB_NAME | default(None) }}"
  - "{{ DISCOVERY_DEFAULT_DB_NAME | default(None) }}"

mysql_database_users:
  - {
      db: "{{ ECOMMERCE_DEFAULT_DB_NAME | default(None) }}",
      user: "{{ ECOMMERCE_DATABASES.default.USER | default(None) }}",
      pass: "{{ ECOMMERCE_DATABASES.default.PASSWORD | default(None) }}"
    }
  - {
      db: "{{ INSIGHTS_DATABASE_NAME | default(None) }}",
      user: "{{ INSIGHTS_DATABASES.default.USER | default(None) }}",
      pass: "{{ INSIGHTS_DATABASES.default.PASSWORD | default(None) }}"
    }
  - {
      db: "{{ ORA_MYSQL_DB_NAME | default(None) }}",
      user: "{{ ORA_MYSQL_USER | default(None) }}",
      pass: "{{ ORA_MYSQL_PASSWORD | default(None) }}"
    }
  - {
      db: "{{ XQUEUE_MYSQL_DB_NAME | default(None) }}",
      user: "{{ XQUEUE_MYSQL_USER | default(None) }}",
      pass: "{{ XQUEUE_MYSQL_PASSWORD | default(None) }}"
    }
  - {
      db: "{{ EDXAPP_MYSQL_DB_NAME | default(None) }}",
      user: "{{ EDXAPP_MYSQL_USER | default(None) }}",
      pass: "{{ EDXAPP_MYSQL_PASSWORD | default(None) }}"
    }
  - {
      db: "{{ EDXAPP_MYSQL_CSMH_DB_NAME | default(None) }}",
      user: "{{ EDXAPP_MYSQL_CSMH_USER | default(None) }}",
      pass: "{{ EDXAPP_MYSQL_CSMH_PASSWORD | default(None) }}"
    }
  - {
      db: "{{ PROGRAMS_DEFAULT_DB_NAME | default(None) }}",
      user: "{{ PROGRAMS_DATABASES.default.USER | default(None) }}",
      pass: "{{ PROGRAMS_DATABASES.default.PASSWORD | default(None) }}"
    }
  - {
      db: "{{ ANALYTICS_PIPELINE_OUTPUT_DATABASE_NAME | default(None) }}",
      user: "{{ ANALYTICS_PIPELINE_OUTPUT_DATABASE.username }}",
      pass: "{{ ANALYTICS_PIPELINE_OUTPUT_DATABASE.password }}"
    }
  - {
      db: "{{ HIVE_METASTORE_DATABASE_NAME | default(None) }}",
      user: "{{ HIVE_METASTORE_DATABASE.user | default(None) }}",
      pass: "{{ HIVE_METASTORE_DATABASE.password | default(None) }}"
    }
  - {
      db: "{{ CREDENTIALS_DEFAULT_DB_NAME | default(None) }}",
      user: "{{ CREDENTIALS_MYSQL_USER | default(None) }}",
      pass: "{{ CREDENTIALS_MYSQL_PASSWORD | default(None) }}"
    }
  - {
      db: "{{ DISCOVERY_DEFAULT_DB_NAME | default(None) }}",
      user: "{{ DISCOVERY_MYSQL_USER | default(None) }}",
      pass: "{{ DISCOVERY_MYSQL_PASSWORD | default(None) }}"
    }

mysql_client_cert: ''
mysql_client_key: ''
mysql_ca_cert: ''
mysql_client_cert_path: '/etc/ssl/certs/mysql-client-cert.pem'
mysql_client_key_path: '/etc/ssl/certs/mysql-client-key.pem'
mysql_ca_cert_path: '/etc/ssl/certs/mysql-server-ca.pem'
mysql_cert_owner: "{{ common_web_user }}"
mysql_cert_group: "{{ common_web_user }}"
