#!/bin/bash
set -e
/sbin/my_init &

# Run Mongo configuration
cd /configuration/playbooks && \
    ansible-playbook run_role.yml -i localhost, -c local \
        -e role=mongo \
        -e@/tmp/server-vars.yml

