---

postgresql_packages:
  - libpq-dev
  - postgresql-client

postgresql_aggregation_requirements:
  - psycopg2

postgresql_aggregation_login_user: "root"
postgresql_aggregation_login_password: "password"
postgresql_aggregation_login_host: "localhost"
postgresql_aggregation_login_port: 5432

POSTGRESQL_AGGREGATION_HOST: "localhost"
POSTGRESQL_AGGREGATION_DATABASE: ""
POSTGRESQL_AGGREGATION_USER: "aggregation_user"
POSTGRESQL_AGGREGATION_PASSWORD: "password"
POSTGRESQL_AGGREGATION_USER_ROLE: "boxes"
