---
- name: Configure shared services (es and memcached)
  hosts: services
  sudo: True
  gather_facts: True
  roles:
    - { role: swapfile, SWAPFILE_SIZE: "4GB" }
    - role: sudo
    - oraclejdk
    - role: elasticsearch
    - role: memcached
    - stackdriver

- name: Configure app server instance(s)
  hosts: edx
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    openid_workaround: True
    EDXAPP_LMS_NGINX_PORT: '80'
    # Set to false if deployed behind another proxy/load balancer.
    NGINX_SET_X_FORWARDED_HEADERS: True
    # These should stay false for the public AMI
    COMMON_ENABLE_DATADOG: False
    COMMON_ENABLE_SPLUNKFORWARDER: False
  roles:
    - { role: swapfile, SWAPFILE_SIZE: "2GB" }
    - role: sudo
    - role: nginx
      nginx_sites:
      - cms
      - lms
      - forum
      nginx_default_sites:
      - lms
    - role: mysql
      when: EDXAPP_MYSQL_HOST == 'localhost'
    - edxlocal
    - role: mongo
      when: "'localhost' in EDXAPP_MONGO_HOSTS"
    # Do we need need edxapp 2 times here????
    - { role: 'edxapp', celery_worker: True }
    - edxapp
    - amc
    #- analytics_api
    #- insights
    - edx_notes_api
    #- demo
    - oauth_client_setup
    - oraclejdk
    - forum
    - edx_ansible
    - stackdriver
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC

- name: Install xqueue, notifier and rabbitmq on services node
  hosts: "services"
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
  roles:
    - edxapp_common
    - role: nginx
      nginx_sites:
      - xqueue
    - { role: 'rabbitmq', rabbitmq_ip: '0.0.0.0' }
    - notifier
    - { role: notifier, NOTIFIER_DIGEST_TASK_INTERVAL: "5" }
    - { role: "xqueue", update_users: True }

# must come after xqueue running
- name: Install certs
  hosts: "edx"
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
  roles:
    - certs
    - role: nginx
      nginx_sites:
      - certs

